name: update-npm-version

# https://github.com/forcedotcom/cli/issues/2327
# Customer needs an npm version that has been bundled with node lts
# We will install the version that is included with the runner's node

on:
  workflow_dispatch:
  schedule:
    # Tuesday 7a central (12 UTC)
    - cron: '0 12 * * 2'

jobs:
  update-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - uses: salesforcecli/github-workflows/.github/actions/yarnInstallWithRetries@main
      - run: |
          echo "package.json npm version: $(jq -r '.dependencies.npm' package.json)"
          echo "GHA Node LTS npm version: $(npm -v)"
          yarn add npm@$(npm -v)
      - uses: salesforcecli/github-workflows/.github/actions/getGithubUserInfo@main
        id: github-user-info
        with:
          token: ${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN }}
      - uses: salesforcecli/github-workflows/.github/actions/gitConfig@main
        with:
          username: ${{ steps.github-user-info.outputs.username }}
          email: ${{ steps.github-user-info.outputs.email }}
      # Push changes if 'git status' is not empty
      - run: |
          if [[ -n $(git status --short) ]]; then
            yarn test
            git add -A
            git commit -m "fix: update npm version"
            git push
          else
            echo "Already up to date"
          fi
